### ISSUE TITLE
The context

### ISSUE THREAD

**Issue by hermanbanken** [lazaridis-com/xeval.typesafe-reactive-platform#2]
Edited by Owner (lazaridis-com)

**github evaluation**

the system allows to edit original issues, **without** leaving any trails (e.g. history), which is a very bad thing, especially for open projects.

Comments of others can be altered (without trails again) adn deleted, too. Strangely, deleting an issue as a whole is not possible.

**Comment by lazaridis-com** [comment]
You should 'reset' how you see Activator.

Activator is an **"Extension to sbt, essentially a project/platform front-end with web-ui"** (source: README of this repo).

Activator is **not** a product, not even a project (it should be part of sbt, or a subproject of sbt). In any case, Activators (very nice and useful) general functionality **must** be provided from the back-scenes (without the term `Activator` appearing everywhere), see typesafehub/activator#995 for a suggested solution.

Thank you for your offer, but I'll not evaluate Play! futher, so any docs are not relevant.

Finally to your question: just see 

https://github.com/lazaridis-com/xeval.jvm-web/blob/master/README.md

it describes context and requirements (which are quite general).

Note that I've done this mostly to get to a personal decision, which I have taken, so I do not invest much more time into this (possibly just writing down some summaries of findings).

Just a final word on Spring:

Spring is a highly flexible Full Stack Application Framework. Yes, it's complex, but the quite new `spring-boot` platform reduces you initial choices, which you can get back, once you master the overall Spring Platform.

**Comment by hermanbanken** [comment]
Ah, so your 'quest' was for this personal decision. Reading your assessment made me think you were doing it for your job or something.

I do not agree with you on that I should 'reset' how I see activator. Currently I do not use activator. I just installed sbt and did `sbt run` and off I go. It's that simple.

I really do not see any use case for the activator UI elements in large, existing, Play applications. This is because it is essentially a tool, and should not be installed on production servers. You know you package Play applications to a jar in the end right? Then you deploy this. No need for activator on the server, just your jars, including Play, for it's core libraries and any of the libraries you selected as dependency in the build file.

Play really excels at being a great framework when you want to use Scala and when your team is expected to be big, or grow over time. Lots of other framework projects become cluttered and unmaintainable over time, but JVM (Scala and Java both) frameworks excel in this, which you know of course.

Also, the way Play incorporates the Reactive Manifesto is not seen before. But we detail upon this in the chapter, if you're interested. It uses an Evented Execution model, with multiple threads (otherwise use NodeJS :unamused:), in stead of the Threaded Execution model. I'm not sure what Spring and Pivotal use, but I'm guessing Threaded...

It makes a great deal of difference if you're doing fancy things like web sockets, or want to be able to serve 60.000 req/s on your application... without having 64GB of RAM (each thread costs you about 1MB).

**Comment by hermanbanken** [comment]
I had a weird feeling, sort of like you were poking and kicking around in all of the Typesafe projects, demanding things to change how you personally feel they should change. While there are discussed roadmaps and plans and idea's already...

This are all large projects (Pivotal, Play, Spring), which have roadmaps, causing me to find it weird if some single developer steps in and demands certain changes...

:walking: just my 2 cents

**Comment by lazaridis-com** [comment]
**github evaluation**

the system allows to edit original issues, **without** leaving any trails (e.g. history), which is a very bad thing, especially for open projects.

Comments of others can be altered (without trails again) adn deleted, too. Strangely, deleting an issue as a whole is not possible.
